service: event-gateway-auth
app: <your-app-name-here>
tenant: <your-tenant-name-here>

plugins:
  - "@serverless/serverless-event-gateway-plugin"

custom:
  eventTypes:
    user.created:
      authorizer: auth

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1

functions:
  auth:
    handler: handler.auth
  main:
    handler: handler.main
    events:
      - eventgateway:
          type: sync
          eventType: user.created
          path: /
          cors: true
